{   "root": true,
    "extends": [
        "eslint:recommended", 
        "plugin:@typescript-eslint/recommended"
    ],
    "parser": "@typescript-eslint/parser",
    "parserOptions": { "project": ["./tsconfig.json"] },
    "plugins": [
        "@typescript-eslint"
    ],
    "rules": {
        "semi": ["error", "always"],
        "quotes": ["error", "double"], 
        "@typescript-eslint/no-inferrable-types": "off",
        "linebreak-style": ["error", "unix"]
    }
}
